# fly.toml app configuration file generated for chat-frontend-0228 on 2024-11-06T17:05:21+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chat-frontend-0228'
primary_region = 'arn'

[build]
  context = "./"
  dockerfile = "Dockerfile"

[env]
  VITE_API_URL = "http://chat-backend-0228.internal:8080/api"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 5173

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1