# name: Deploy to Fly.io

# on:
#   push:
#     branches:
#       - main # 監聽 main 分支，當有推送到 main 時觸發部署

# jobs:
#   deploy-db:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out the code
#         uses: actions/checkout@v4

#       - name: Set up Fly.io CLI
#         uses: superfly/flyctl-actions/setup-flyctl@master

#       - name: Deploy chat-db-0228 to Fly.io
#         env:
#           FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
#           MYSQL_USER: ${{ secrets.DB_USER }}
#           MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
#           MYSQL_DATABASE: ${{ secrets.DB_NAME }}
#           MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
#         run: |
#           flyctl deploy

#   deploy-frontend:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out the code
#         uses: actions/checkout@v4

#       - name: Set up Fly.io CLI
#         uses: superfly/flyctl-actions/setup-flyctl@master

#       - name: Deploy chat-frontend-0228 to Fly.io
#         env:
#           FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
#           GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
#         run: |
#           flyctl deploy

#   deploy-server:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out the code
#         uses: actions/checkout@v4

#       - name: Set up Fly.io CLI
#         uses: superfly/flyctl-actions/setup-flyctl@master

#       - name: Deploy chat-server-0228 to Fly.io
#         env:
#           FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
#           DB_USER: ${{ secrets.DB_USER }}
#           DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
#           DB_HOST: ${{ secrets.DB_HOST }}
#           DB_PORT: ${{ secrets.DB_PORT }}
#           DB_NAME: ${{ secrets.DB_NAME }}
#           GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
#         run: |
#           flyctl deploy
